### ISSUE TITLE
exception when trying to open panel

### ISSUE THREAD

**Issue by move-tool** [move-tool/gephi-plugins#2]
When trying to switch to the tool's panel `Windows/NetworkOptimization`

The following exception is thrown:

```
 java.lang.IllegalStateException: Cannot find TopComponent with preferredID NetworkOptimizationPanelTopComponent, see IDE log for more details.
[INFO]  at org.openide.windows.OpenComponentAction.actionPerformed(OpenComponentAction.java:91)
[INFO]  at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:199)
[INFO]  at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:95)
[INFO]  at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
[INFO]  at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
[INFO]  at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:202)
[INFO]  at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
[INFO]  at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
[INFO]  at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
[INFO]  at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
[INFO]  at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
[INFO]  at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
[INFO]  at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
[INFO]  at java.awt.Component.processMouseEvent(Component.java:6535)
[INFO]  at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
[INFO]  at java.awt.Component.processEvent(Component.java:6300)
[INFO]  at java.awt.Container.processEvent(Container.java:2236)
[INFO]  at java.awt.Component.dispatchEventImpl(Component.java:4891)
[INFO]  at java.awt.Container.dispatchEventImpl(Container.java:2294)
[INFO]  at java.awt.Component.dispatchEvent(Component.java:4713)
[INFO]  at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
[INFO]  at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
[INFO]  at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
[INFO]  at java.awt.Container.dispatchEventImpl(Container.java:2280)
[INFO]  at java.awt.Window.dispatchEventImpl(Window.java:2750)
[INFO]  at java.awt.Component.dispatchEvent(Component.java:4713)
[INFO]  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
[INFO]  at java.awt.EventQueue.access$500(EventQueue.java:97)
[INFO]  at java.awt.EventQueue$3.run(EventQueue.java:709)
[INFO]  at java.awt.EventQueue$3.run(EventQueue.java:703)
[INFO]  at java.security.AccessController.doPrivileged(Native Method)
[INFO]  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
[INFO]  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[INFO]  at java.awt.EventQueue$4.run(EventQueue.java:731)
[INFO]  at java.awt.EventQueue$4.run(EventQueue.java:729)
[INFO]  at java.security.AccessController.doPrivileged(Native Method)
[INFO]  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
[INFO]  at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
[INFO]  at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)

```

**Comment by move-tool** [comment]
running from within netbeans provides a more informative error:

```
INFO [org.netbeans.core.windows.persistence]: [PersistenceManager.getTopComponentForID] Problem when deserializing TopComponent for tcID:'NetworkOptimizationPanelTopComponent'. Reason: null
Offending classloader: ModuleCL@4aeb30dc[org.activeintel.move]
Content: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings PUBLIC "-//NetBeans//DTD Session settings 1.0//EN" "http://www.netbeans.org/dtds/sessionsettings-1_0.dtd">
<settings version="1.0">
  <instance class="org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationPanelTopComponent"/>
</settings>
Class: class org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationPanelTopComponent
Source: MultiFileObject@3fb66cc8[Windows2Local-overview/Components/NetworkOptimizationPanelTopComponent.settings]
Offending classloader: ModuleCL@4aeb30dc[org.activeintel.move]
Content: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings PUBLIC "-//NetBeans//DTD Session settings 1.0//EN" "http://www.netbeans.org/dtds/sessionsettings-1_0.dtd">
<settings version="1.0">
  <instance class="org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationPanelTopComponent"/>
</settings>
Class: class org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationPanelTopComponent
Source: MultiFileObject@3fb66cc8[Windows2Local-overview/Components/NetworkOptimizationPanelTopComponent.settings]
Caused: java.util.MissingResourceException: No such bundle org.activeintel.network.optimization.algorithms.ui.Bundle
    at org.openide.util.NbBundle.getBundle(NbBundle.java:451)
    at org.openide.util.NbBundle.getBundle(NbBundle.java:399)
    at org.openide.util.NbBundle.getMessage(NbBundle.java:642)
    at org.activeintel.network.optimization.algorithms.ui.SubGraphEvaluationCriteriaPanel.initComponents(SubGraphEvaluationCriteriaPanel.java:57)
    at org.activeintel.network.optimization.algorithms.ui.SubGraphEvaluationCriteriaPanel.<init>(SubGraphEvaluationCriteriaPanel.java:37)
    at org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationPanelTopComponent.initComponents(NetworkOptimizationPanelTopComponent.java:91)
    at org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationPanelTopComponent.<init>(NetworkOptimizationPanelTopComponent.java:64)
Caused: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.netbeans.modules.settings.convertors.XMLSettingsSupport.newInstance(XMLSettingsSupport.java:100)
    at org.netbeans.modules.settings.convertors.XMLSettingsSupport$SettingsRecognizer.instanceCreate(XMLSettingsSupport.java:628)
Caused: java.io.IOException
    at org.netbeans.modules.settings.convertors.XMLSettingsSupport$SettingsRecognizer.instanceCreate(XMLSettingsSupport.java:630)
    at org.netbeans.modules.settings.convertors.SerialDataConvertor$SettingsInstance.instanceCreate(SerialDataConvertor.java:426)
[catch] at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentPersistentForID(PersistenceManager.java:571)
    at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentForID(PersistenceManager.java:681)
    at org.netbeans.core.windows.PersistenceHandler.getTopComponentForID(PersistenceHandler.java:478)
    at org.netbeans.core.windows.WindowManagerImpl.getTopComponentForID(WindowManagerImpl.java:962)
    at org.netbeans.core.windows.WindowManagerImpl.findTopComponent(WindowManagerImpl.java:292)
    at org.openide.windows.OpenComponentAction.getTopComponent(OpenComponentAction.java:76)
    at org.openide.windows.OpenComponentAction.actionPerformed(OpenComponentAction.java:89)
    at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:199)
    at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:95)
    at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
    at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
    at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:202)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ALL [null]: Offending classloader: ModuleCL@4aeb30dc[org.activeintel.move]
Content: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings PUBLIC "-//NetBeans//DTD Session settings 1.0//EN" "http://www.netbeans.org/dtds/sessionsettings-1_0.dtd">
<settings version="1.0">
  <instance class="org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationPanelTopComponent"/>
</settings>
ALL [null]: Class: class org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationPanelTopComponent
ALL [null]: Source: MultiFileObject@3fb66cc8[Windows2Local-overview/Components/NetworkOptimizationPanelTopComponent.settings]
INFO [org.netbeans.core.startup.layers.BinaryFS]: value = org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationPanelTopComponent from Actions/Window/org-activeintel-gephi-network-optimization-genetic-ui-NetworkOptimizationPanelTopComponent.instance
Offending classloader: ModuleCL@4aeb30dc[org.activeintel.move]
Offending classloader: ModuleCL@4aeb30dc[org.activeintel.move]
Caused: java.util.MissingResourceException: No such bundle org.activeintel.network.optimization.algorithms.ui.Bundle
    at org.openide.util.NbBundle.getBundle(NbBundle.java:451)
    at org.openide.util.NbBundle.getBundle(NbBundle.java:399)
    at org.openide.util.NbBundle.getMessage(NbBundle.java:642)
    at org.activeintel.network.optimization.algorithms.ui.SubGraphEvaluationCriteriaPanel.initComponents(SubGraphEvaluationCriteriaPanel.java:57)
    at org.activeintel.network.optimization.algorithms.ui.SubGraphEvaluationCriteriaPanel.<init>(SubGraphEvaluationCriteriaPanel.java:37)
    at org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationPanelTopComponent.initComponents(NetworkOptimizationPanelTopComponent.java:91)
    at org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationPanelTopComponent.<init>(NetworkOptimizationPanelTopComponent.java:64)
Caused: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[catch] at org.netbeans.core.startup.layers.BinaryFS$AttrImpl.getValue(BinaryFS.java:712)
    at org.netbeans.core.startup.layers.BinaryFS$BFSBase.getAttribute(BinaryFS.java:549)
    at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:944)
    at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:877)
    at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:940)
    at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:877)
    at org.openide.filesystems.MultiFileObject.getAttribute(MultiFileObject.java:798)
    at org.netbeans.core.startup.layers.BinaryFS$FileMap.get(BinaryFS.java:1128)
    at org.openide.windows.OpenComponentAction.getTopComponent(OpenComponentAction.java:79)
    at org.openide.windows.OpenComponentAction.actionPerformed(OpenComponentAction.java:89)
    at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:199)
    at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:95)
    at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
    at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
    at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:202)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ALL [null]: Offending classloader: ModuleCL@4aeb30dc[org.activeintel.move]
SEVERE [global]
java.lang.IllegalStateException: Cannot find TopComponent with preferredID NetworkOptimizationPanelTopComponent, see IDE log for more details.
    at org.openide.windows.OpenComponentAction.actionPerformed(OpenComponentAction.java:91)
    at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:199)
    at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:95)
    at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
    at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
    at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:202)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by move-tool** [comment]
opening panel in IDE throws the following exception:
(seems that `SubGraphEvaluationCriteriaPanel.java` is missing)

```
java.util.MissingResourceException: No such bundle org.activeintel.network.optimization.algorithms.ui.Bundle
    at org.openide.util.NbBundle.getBundle(NbBundle.java:451)
    at org.openide.util.NbBundle.getBundle(NbBundle.java:399)
    at org.openide.util.NbBundle.getMessage(NbBundle.java:642)
    at org.activeintel.network.optimization.algorithms.ui.SubGraphEvaluationCriteriaPanel.initComponents(SubGraphEvaluationCriteriaPanel.java:57)
    at org.activeintel.network.optimization.algorithms.ui.SubGraphEvaluationCriteriaPanel.<init>(SubGraphEvaluationCriteriaPanel.java:37)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at java.lang.Class.newInstance(Class.java:442)
    at org.netbeans.modules.form.CreationFactory.createDefaultInstance(CreationFactory.java:178)
    at org.netbeans.modules.form.RADComponent.createBeanInstance(RADComponent.java:252)
    at org.netbeans.modules.form.RADComponent.initInstance(RADComponent.java:191)
    at org.netbeans.modules.form.GandalfPersistenceManager.restoreComponent(GandalfPersistenceManager.java:780)
    at org.netbeans.modules.form.GandalfPersistenceManager.loadComponent(GandalfPersistenceManager.java:968)
    at org.netbeans.modules.form.GandalfPersistenceManager.restoreComponent(GandalfPersistenceManager.java:824)
    at org.netbeans.modules.form.GandalfPersistenceManager.loadComponent(GandalfPersistenceManager.java:968)
    at org.netbeans.modules.form.GandalfPersistenceManager.loadForm(GandalfPersistenceManager.java:503)
    at org.netbeans.modules.form.GandalfPersistenceManager.loadForm(GandalfPersistenceManager.java:283)
    at org.netbeans.modules.form.FormEditor$2.run(FormEditor.java:352)
    at org.netbeans.modules.form.FormLAF$2.run(FormLAF.java:293)
    at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:138)
    at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:98)
    at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:94)
    at org.openide.util.Mutex.readAccess(Mutex.java:250)
    at org.netbeans.modules.form.FormLAF.executeWithLookAndFeel(FormLAF.java:276)
    at org.netbeans.modules.form.FormEditor.loadFormData(FormEditor.java:349)
    at org.netbeans.modules.nbform.FormEditorSupport.loadOpeningForm(FormEditorSupport.java:468)
    at org.netbeans.modules.nbform.FormDesignerTC.loadForm(FormDesignerTC.java:279)
    at org.netbeans.modules.nbform.FormDesignerTC.access$300(FormDesignerTC.java:87)
    at org.netbeans.modules.nbform.FormDesignerTC$PreLoadTask$1.run(FormDesignerTC.java:268)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: Offending classloader: org.netbeans.modules.form.project.ProjectClassLoader@d04a337

```

**Comment by move-tool** [comment]
`java.util.MissingResourceException: No such bundle org.activeintel.network.optimization.algorithms.ui.Bundle`

**Comment by move-tool** [comment]
`java.util.MissingResourceException: Can't find resource for bundle org.openide.util.NbBundle$PBundle, key SubGraphEvaluationCriteriaPanel.loadMetricsBtn.text`
