### ISSUE TITLE
java.lang.IllegalArgumentException: The column 'PageRank' is not found

### ISSUE THREAD

**Issue by move-tool** [move-tool/gephi-plugins#4]
```
java.lang.IllegalArgumentException: The column 'PageRank' is not found
    at org.gephi.graph.impl.ElementImpl.checkColumnExists(ElementImpl.java:710)
    at org.gephi.graph.impl.ElementImpl.getAttribute(ElementImpl.java:89)
    at org.activeintel.network.optimization.algorithms.SubGraphEvaluator.getFitness(SubGraphEvaluator.java:165)
    at org.activeintel.network.optimization.algorithms.SubGraphEvaluator.getFitness(SubGraphEvaluator.java:206)
    at org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationTask.init(NetworkOptimizationTask.java:146)
    at org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationTask.doInBackground(NetworkOptimizationTask.java:181)
    at org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationTask.doInBackground(NetworkOptimizationTask.java:58)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at javax.swing.SwingWorker.run(SwingWorker.java:334)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused: java.util.concurrent.ExecutionException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at javax.swing.SwingWorker.get(SwingWorker.java:602)
[catch] at org.activeintel.gephi.network.optimization.genetic.ui.NetworkOptimizationTask.done(NetworkOptimizationTask.java:80)
    at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
    at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
    at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
    at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
    at javax.swing.Timer.fireActionPerformed(Timer.java:313)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by move-tool** [comment]
node.getAttribute() doesn't work reliably with a string key; used column key instead.
